### ISSUE TITLE
Option to create JSON output in the same structure as the 0.8 parser

### ISSUE THREAD

**Issue by oberlies** [raml-org/raml-js-parser-2#11]
The parser for [RAML 0.8 parser](https://github.com/raml-org/raml-js-parser) produces a JavaScript object that has a different structure than the RAML file itself. E.g. resources are grouped in an "resources" property.

The new parser should have an option to produce the same format, e.g. for compatibility with [raml2html](https://github.com/kevinrenskers/raml2html)

**Comment by petrochenko-pavel-a** [comment]
@oberlies this is important question for discussion. We definitely can create some kind of converter , but it will not help you much with implementing actual support for  RAML 1.0 features.

Regards,
Pavel

**Comment by oberlies** [comment]
The major difference in the output is that the resources are stored as raw properties by the 1.0 parser and not grouped in a "resources" property. This makes the output of the 1.0 parser a lot harder to consume.

Are there any plans to re-introduce the "resources" property in the parser output? BTW, is there a specification of the structure produced by the parser?

**Comment by sichvoge** [comment]
I can't help you with your first question, but you can find the structure [here](https://raml-org.github.io/raml-js-parser-2/). Let me know if that is what you were looking for. We are still improving the parser and how people consume it, so every feedback is very welcome. ;)

**Comment by oberlies** [comment]
@sichvoge Thanks a lot for this link - this is very helpful.

**Comment by thenanox** [comment]
I'm really interested in this topic. I was thinking about adding a property into toJSON [serializeOptions](https://raml-org.github.io/raml-js-parser-2/interfaces/_raml1_jsyaml_json2lowlevel_.serializeoptions.html) because of resources that are not nested now. IS very different vs 0.8 parser, and also it makes the collection harder to iterate, and personally, inconsistent with the rest of the toJSON structure.

Also i checked that some properties are read as string instead of boolean or number such as required property. This may also be changed so json structure is better.

What do you think?

**Comment by petrochenko-pavel-a** [comment]
`toJSON` output is pretty similar to 0.8 at this point, so closing this.  Please report if you see something that still needs improvement.

Regards,
Pavel

**Comment by naterkane** [comment]
@petrochenko-pavel-a which commit or tag gave you the confidence to close this issue?
