### ISSUE TITLE
Obtaining types defined in Libraries (included via uses) in JSON output

### ISSUE THREAD

**Issue by juancoen** [raml-org/raml-js-parser-2#132]
When parsing a RAML file that includes types/schemas included via Libraries with uses, the toJSON output of the parser is:
```
{
  "schemas": [
    {
      "Player": {
        "name": "Player",
        "displayName": "Player",
        "type": [
          "{\n  \"type\": \"object\",\n  \"properties\": [\n    {\n      \"name\": \"string\"\n    }\n  ]\n}\n"
        ],
        "repeat": false,
        "required": true
      }
    }
  ],
  "title": "API with Library",
  "version": "1",
  "resources": [
    {
      "methods": [
        {
          "responses": {
            "201": {
              "code": "201",
              "body": {
                "application/json": {
                  "name": "application/json",
                  "displayName": "application/json",
                  "type": [
                    "file-type.File"
                  ],
                  "repeat": false,
                  "required": true
                }
              }
            },
            "203": {
              "code": "203",
              "body": {
                "application/json": {
                  "name": "application/json",
                  "displayName": "application/json",
                  "schema": [
                    "person-schema.Person"
                  ],
                  "repeat": false,
                  "required": true
                }
              }
            }
          },
          "method": "get"
        }
      ],
      "relativeUri": "/test",
      "displayName": "/test",
      "relativeUriPathSegments": [
        "test"
      ]
    }
  ],
  "uses": [
    {
      "name": "file-type",
      "value": "libraries/file-type.raml"
    },
    {
      "name": "person-schema",
      "value": "libraries/person-schema.`raml"
    }
  ]
}
```

`uses` returns relative paths as values and type/schema return the namespaced type/schema reference, but there is no easy way to access its content.

This is the code used to obtain the RAML JSON:

```
eturn RAML.Parser.loadApi(path, {
          attributeDefaults: true,
          rejectOnErrors:    true,
          fsResolver:        {
            contentAsync: contentAsyncFn,
            content:      content
          },
          httpResolver:      {
            getResourceAsync: function getResourceAsync(url) {
              var proxy = (($window.RAML || {}).Settings || {}).proxy || '';
              return $http.get(proxy + url, {transformResponse: null})
                .then(function (res) {
                  return {content: res.data};
                })
              ;
            },
            getResource: getResource
          }
        })
          .then(function (api) {
            api = api.expand();
            return api.toJSON();
          })
        ;
```
Note that `expand` is being called

How is this supposed to be used?

Thanks

**Comment by ddenisenko** [comment]
Right now, the way to obtain library AST is to get the final link from the uses node and call loadRAML() for the file.
We do agree, that this is not very convenient.

Here is the list of changes to implement in order to make RC2 fragments (libraries etc) more accessible.
It is not a final decision, but most probably what will be implemented:

1) Api, Library, Extension and Overlay will now directly implement FragmentDeclaration, which does contain uses() method returning the list of uses for this fragment.

2) Types, Annotations, Traits, Resource types, Examples and Documentation items will now optionally implement FragmentDeclaration. By "optional implementation" I mean that user can call static top-level method `isFragment()` for nodes of listed kinds and in case of getting "true" may cast an instance of the node to FragmentDeclaration (maybe we will also add a casting method `asFragment()`) and then work with this node as with FragmentDeclaration.

3) loadRAML() top-level method will now return FragmentDeclaration instead of BasicNode.

4) UsesDeclaration node, obtainable from FragmentDeclaration will now have a helper method `ast()` returning AST of the fragment, it references.

5) TCK dumper will automatically call listed methods for all fragments guaranteeing that any fragment node will have `uses` property listing the uses if there are actually some uses declared by user.

What that means for toJSON() users:

1) At the top level of APi, Library, and any other fragment you will always see `uses`, if there are any

2) You can obtain UsesDeclaration nodes of those uses by a simple call to `topLevelNode.uses()`

3) For each UsesDeclaration in an array returned by `topLevelNode.uses()` you will be able to check its name by calling `key()` and obtain ast of the referred fragment by calling `ast()`. File name does not matter any more.

4) For obtained ast of the fragment (library etc), you will be able to call `toJSON()` and work with it as usual. Including creating name->type map, Juan was using before.

**Comment by juancoen** [comment]
thanks @ddenisenko 

any estimation on how will this be ready?

**Comment by ddenisenko** [comment]
Implemented.

The changes, compared to what was planned (listed above):
1) UsesDeclaration#ast() does return Library instead of FragmentDeclaration as right now uses can only reference libraries.
2) loadRAML still returns BasicNode instead of FragmentDeclaration as this method can be used for both RAML 0.8 and 1.0, and there are no fragments in RAML 0.8.

A quick sample of uses handling:

RAML1:
```
#%RAML 1.0
title: API with Library
version: 1

uses:
  AnimalLibrary: library.raml
``` 

library.raml:
```
#%RAML 1.0 ResourceType

#This file is located at resourceTypes/collection.raml

description: A collection resource
usage: Use this to describe resource that list items
get:
  description: Retrieve all items
post:
  description: Add an item
  responses:
    201:
      headers:
        Location:
```

JS:
```js
console.log(JSON.stringify(api.toJSON({rootNodeDetails: false, serializeMetadata: false}), null, 2));

    console.log("---------------------!")

    var isFragment = raml.isFragment(api);
    api.uses().forEach(function(use){
        var useAst = use.ast();
        console.log(JSON.stringify(useAst.toJSON({rootNodeDetails: false, serializeMetadata: false}), null, 2));
    })
```

Output:
```
{
  "uses": [
    {
      "key": "AnimalLibrary",
      "value": "library.raml"
    }
  ],
  "title": "API with Library",
  "version": "1"
}
---------------------!
{
  "types": [
    {
      "Animal": {
        "name": "Animal",
        "properties": {
          "name": {
            "name": "name",
            "type": [
              "string"
            ]
          }
        }
      }
    }
  ]
}
```
