### ISSUE TITLE
Examples should not be validated against schemas in RAML 0.8

### ISSUE THREAD

**Issue by juancoen** [raml-org/raml-js-parser-2#133]
In RAML 0.8, validating examples was not part of the spec. The new parser is validating them which may cause multiple "valid" RAML 0.8 specs to become invalid for the new parser.

**Comment by ddenisenko** [comment]
I do not agree. 

Spec does not determine whether the parser should validate it, or not, its up to the parser.

Validating examples against the schemas make user's APIs better. Instead of hiding errors, those schema errors should be fixed.

**Comment by sichvoge** [comment]
I do not agree as well; if you have an invalid RAML we should notify the designer that there is something wrong. RAML is a "generic" non-programming-language specific language that should work the same regardless of what parser you work with. The expected behaviour in most cases is that when your given example match against your schema, it's an error in the spec. Do you want to find out that there is a problem with your spec at runtime or deisgn time where you can easily fix it. Remember that people use examples to make their first attempt to your API. If they do not work, they likely to go away.

**Comment by juancoen** [comment]
I understand that validating examples against schemas is the *correct* thing to do. However, what I'm saying is that it might be problematic for RAML 0.8 backwards compatibility.

Given that the old RAML 0.8 parser wasn't doing this validation, and that this was a blind spot in the spec, there might be lots of RAML 0.8 definitions out there that will be broken overnight once the parser is updated to the new version and this could produce lots of support cases.

What I'm suggesting is to convert this validation errors to warnings for this first version so that people can correct them at their own pace. In subsequent versions of the parser they can be changed back to errors.

Thanks

**Comment by juancoen** [comment]
Another option is to add a flag to turn off this validation for our particular case.

**Comment by sichvoge** [comment]
@juancoen, you can't leave people with wrong specifications. that might not get notified using the API Designer, but what about other tools? Commonly everything that was then used with tooling that are underpinned by the Java parser rejected that RAML. That created all sorts of problems which are fixed now. Its not that we "break" existing RAML definitions, we actually make them correct so that there are no problems when using the same definition with other tools.

**Comment by petrochenko-pavel-a** [comment]
Hm, as agreed with @sichvoge I changed loader to do not reject apis which contains warnings. example vs schema validation already reported them as a warnings so no change was required in this area. @dreamflyer please consider it when dealing with #136
