### ISSUE TITLE
error message is not useful for invalid use of sub resources in resource types and traits

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#325]
![image](https://cloud.githubusercontent.com/assets/498114/16449546/0229ab68-3df0-11e6-82b5-a03de4c3abdd.png)

The error message "Unknown node: /groups" is not really useful. Can we be a bit more specific that highlights that a sub resource in a resource type (or trait) is not allowed.

**Comment by ddenisenko** [comment]
Unfortunately, we cant. The issue is that the structure is what defines whether `/groups` string is a resource, or whatever else. So what we see here is an unknown node, its not a misplaced resource.

Theoretically, we can try to *guess* that user meant it to be a resource by looking for a `/` character in the beginning, but that is rather weak base for guessing.

Also, if we start to make guesses, there are lots and lots of other cases where we could, theoretically, try to guess what user meant instead of what was actually typed, and all of those cases would be manually written code, not something calculated based on declarations in the definition system as it is now.

**Comment by KonstantinSviridov** [comment]
We could detect usages of properties starting with '/' in all inappropriate places and produce the following message:

Subresources are not allowed in <<typeName | !pluralize | ! tosentencecase |! tolowercase>>.

Here I mean aaplying those JS functions which are used in RAML functions impllementation.
For example "ResourceType" string will be transformed in the following way:
```
ResourceType --(!pluralize)->ResourceTypes --(!tosentenceCase)-> Resource types --(!tolowercase)-> resource types
```
