### ISSUE TITLE
Release file size

### ISSUE THREAD

**Issue by abdvl** [raml-org/raml-js-parser-2#432]
I notice 1.0.0 & 0.2.33 & 0.2.32 release file size is quite big, around 17MB. Is there any way to reduce size? maybe remove webpack dev dependences.

**Comment by sichvoge** [comment]
Hi @abdvl, we will make some significant improvements to the overall parser architecture and also remove dependencies that are not necessary. We currently work on a plan for that. Stay tuned.

**Comment by KonstantinSviridov** [comment]
Hi everyone

The plan is to
1. Apply refactoring in order to remove some of the dependencies
2. Remove XML validation from default build as the validation module now takes fore then half of the size.  XML validation is going to be optional or available in alternative build.

These modification will reduce file size up to 3-4 times.

**Comment by petrochenko-pavel-a** [comment]
Q: what about removing JSON schema support from default bundle to?

**Comment by KonstantinSviridov** [comment]
@petrochenko-pavel-a It seems that there is no need for doing so: the z-schema module is small, and it shares each dependency with some other parser dependency module.

**Comment by ddenisenko** [comment]
Parser size reduced to 3.4 mb unzipped.
XML validation is extracted from the parser.
Parser NPM does not depend on `raml-xml-validation` package directly. If `raml-xml-validation` module presents, XML validation will be performed by the parser, otherwise XML validation is skipped.

Web version of the parser now contains two JS files: `raml-1-parser.js` and `raml-xml-validation.js`.
Including `raml-xml-validation.js` is optional and enables XML validation.

`examples/web-example/index.html` inside web package demonstrates how to include both parser and optional validation:

```
        <script type="text/javascript" src="../../raml-xml-validation.js"></script>
        <script type="text/javascript" src="../../raml-1-parser.js"></script>
```

**Comment by ddenisenko** [comment]
Parser size is now 3.3 mb instead of 17 mb, unarchived. We should see if we can reduce size more.

**Comment by sichvoge** [comment]
Whats the size with the JSON and XML validation?

**Comment by ddenisenko** [comment]
JSON validation: 204KB, XML validation: 10.7MB unarchived.

**Comment by sichvoge** [comment]
> XML validation: 10.7MB
What? :D

Is that minimized already?

**Comment by sichvoge** [comment]
@ddenisenko can we review this https://github.com/kripken/xml.js/issues/15. seems there is a smaller version.

**Comment by abdvl** [comment]
@ddenisenko  you guys awesome! Now i can consider to move to latest version of api-console.

**Comment by KonstantinSviridov** [comment]
@ddenisenko I do not see further possibilities to decrease the size

**Comment by KonstantinSviridov** [comment]
(In fact, we expect to drop about 250kb by removing top level AST)

**Comment by ddenisenko** [comment]
@sichvoge :

Figures:

Parser before size reduction, not minified, not zipped:
raml-1-parser.js - 17.3 Mb

Parser after size reduction and split into the main part and plugins, not minified, not zipped:
raml-1-parser.js - 3.3 Mb
raml-json-validation.js - 0.19 Mb
raml-xml-validation.js - 10.7 Mb
Total: 14.9 Mb

Parser after size reduction and split into the main part and plugins, minified, not zipped:
raml-1-parser.js - 1.4 Mb
raml-json-validation.js - 0.077 Mb
raml-xml-validation.js - 4.3 Mb
Total: 5.777 Mb

Parser after size reduction and split into the main part and plugins, minified, zipped:
Total: 1.1 Mb
