### ISSUE TITLE
XML Example validation failure

### ISSUE THREAD

**Issue by petrochenko-pavel-a** [raml-org/raml-js-parser-2#461]
Hi, I am expiriencing strange validation messages with following RAML example:

``` raml
#%RAML 1.0 Library
types:
  Person:
    properties:
      name:
        type: string
        xml:
          attribute: true
      lastName:
        type: string
        xml:
          name: last
          attribute: true
  Manager:
    type: Person
    properties:
      manages:
        type: Person[]
        xml:
          wrapped: true
    example: |
      <Manager >
        <name>Ada</name>
        <lastName>Dog</lastName>
        <manages></manages>
      </Manager>
```

Thanks in advance,
Pavel

**Comment by petrochenko-pavel-a** [comment]
Sorry, I am idiot.

**Comment by petrochenko-pavel-a** [comment]
Hm, but following still not works
```raml
#%RAML 1.0 Library
types:
  Person:
    xml:
      name: person
    properties:
      name:
        type: string

      lastName:
        type: string

  Manager:
    type: Person
    properties:
      manages:
        type: Person[]
        xml:
          wrapped: true
    example: |
      <Manager>
        <name>Ada</name>
        <lastName>Dog</lastName>
        <manages><person><name>Pavel</name><lastName>Petrochenko</lastName></person></<manages>
      </Manager>
```
And actually it looks like spec needs a bit more clarifications about it wrapped+inner element names to.

Regards, Pavel

**Comment by sichvoge** [comment]
I think the behaviour you are seeing is because we externalized the XML validation to reduce the size of the parser. There is an additional js file that you can use to run it. See here https://github.com/raml-org/raml-js-parser-2/issues/432#issuecomment-246903796

**Comment by sichvoge** [comment]
We definitely need to be more clear what the default validations are, that the parser does OOTB.

**Comment by ddenisenko** [comment]
No, this is not happening due to the split of the parser into parts.

This is a real bug, or, actually two separate bugs.

The first one is regarding validation reaction to Pavel's XML: the XML is invalid and this causes Error to be thrown, and that error is not being handled. In the latest example we need to report a more meaningful error. 

The second bug, after XML correction is that there is certainly something wrong about type definition+example+validation, I cant make it work. And, I dont really even know how this -should- work. So yes, we need a proper description for wrapping+properties (inner elements), and moreover for wrapping+properties+arrays.

**Comment by KonstantinSviridov** [comment]
Hi, @petrochenko-pavel-a 

The parser accepts your example after applying some corrections to it:
```raml
#%RAML 1.0 Library
types:
  Person:
    xml:
      name: person
    properties:
      name:
        type: string

      lastName:
        type: string

  Manager:
    type: Person
    properties:
      manages:
        type: Person[]
        xml:
          wrapped: true
    example: |
      <Manager>
        <name>Ada</name>
        <lastName>Dog</lastName>
        <manages><Person><name>Pavel</name><lastName>Petrochenko</lastName></Person></manages>
      </Manager>
```
The array component tag must be `Person`, not 'person'.
