### ISSUE TITLE
schema references included with in another schema is not validated properly

### ISSUE THREAD

**Issue by ulaBLUE** [raml-org/raml-js-parser-2#580]
Hello,
I have schema (a.xsd) that includes another schema b.xsd as shown below.

`<xs:include schemaLocation="b.xsd" />`

In API workbench, if I try to refer an example (that is perfectly valid as per a.xsd) like below, there is a validation error as shown below.  It fails in RAML2HTML (latest version) as well , so it is an issue with the parser.

`example: !include examples/a1.xml`

**erorr**

> Example does not conform to schema: Content is not valid according to schema: warning: failed to load external entity "b.xsd", file_0.xsd:4: element include: Schemas parser error : Element '{http://www.w3.org/2001/XMLSchema}include': Failed to load the document 'b.xsd' for inclusion.at line 226 col 15

**Comment by edjannoo** [comment]
This also affects JSON schemas - the circumstances under which this occurs are:
- the RAML file uses ```!include``` to pull in a schema from a subdirectory of where the RAML file itself resides
- the schema uses ```$ref``` to include a definition from another schema file using a path relative to the location of the including schema

See also https://github.com/raml2html/raml2html/issues/294

**Comment by ddenisenko** [comment]
>I have schema (a.xsd) that includes another schema b.xsd as shown below...

I confirm there is a shortcoming on parser side regarding XSD including another XSD. It looks like there is a way around to make the JS version of xmllint we use to understand several schemas if we feed it with an array of such schemas (by manually analyzing the dependencies) and patch include locations. We'll see if it works.

@edjannoo Your issue is not related to the OP XSD one, so I am moving it to a separate ticket. Please see the answer there: https://github.com/raml-org/raml-js-parser-2/issues/583

**Comment by dreamflyer** [comment]
will be published in v1.1.13.

**Comment by ulaBLUE** [comment]
I find it is not working with latest api-workbench version 0.8.43. My use case is when I include schema using xsd:include which is in same namespace. I think below error requires me to use xsd:import. So is this not fixed for xsd:include cases ?

The error is

Example does not conform to schema: Content is not valid according to schema: file_2.xsd:32: element element: Schemas parser error : Element '{http://www.w3.org/2001/XMLSchema}element', attribute 'ref': The QName value 'office' does not resolve to a(n) element declaration.

**Comment by ddenisenko** [comment]
This kind of referencing works in a general case, but there are potential corner cases possible. In example, recently it was discovered that such a referencing fails when schema name is being passed  as a parameter of resource type for 0.8 RAML only, here: https://github.com/raml-org/raml-js-parser-2/issues/700

Could you please provide minimal viable example, or any example that you can publish, so that we can check your particular case.

**Comment by ddenisenko** [comment]
Examples requires RAML, schemas and example.

**Comment by ulaBLUE** [comment]
sorry, today I found it working against my samples. Btw I have updated new version. 
Thanks for your time. I'm closing this issue.
