### ISSUE TITLE
RAML-parser: error while using 'type' and 'example' in request body.

### ISSUE THREAD

**Issue by badrinathwrk** [raml-org/raml-js-parser-2#589]
Hello team,

I am trying to use RAML 1.0.
where i created an api which accepts xml as an request.
There is an error while i use 'type' and 'example' in request body.

'commonTypes.xsd' has two elements which is imported in 'customerTypes.xsd'.

 __commonTypes.xsd__
```xml
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="http://www.test.com/common"
		   xmlns="http://www.test.com/common">
       <xs:simpleType name="lastName">
     		<xs:restriction base="xs:string">
     			<xs:maxLength value="5"/>
     		</xs:restriction>
     	</xs:simpleType>
      <xs:simpleType name="Language">
    		<xs:restriction base="xs:string">
    			<xs:enumeration value="DE"/>
    			<xs:enumeration value="EN"/>
    			<xs:enumeration value="FR"/>
    			<xs:enumeration value="NL"/>
    		</xs:restriction>
    	</xs:simpleType>
</xs:schema>
```
__CustomerTypes.xsd__
```xml
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
   targetNamespace="http://www.test.com/request/create"
   xmlns="http://www.test.com/request/create"
   xmlns:com="http://www.test.com/common">
<xs:import namespace="http://www.test.com/common" schemaLocation="CommonTypes.xsd"/>
<xs:element name="customerDetails" type="customerDetails"/>
   <xs:complexType name="customerDetails">
   <xs:sequence>
      <xs:element name="firstName" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="lastName" type="com:lastName" minOccurs="1" maxOccurs="1"/>
      <xs:element name="language" type="com:Language" minOccurs="1" maxOccurs="1"/>
   </xs:sequence>
  </xs:complexType>
</xs:schema>
```
Below is the xml for the above schema
__customerDetailsXML.xml__
```xml
<?xml version="1.0" encoding="utf-8"?>
<customerDetails>
  <firstName>str1234</firstName>
  <lastName>str12</lastName>
  <language>DE</language>
</customerDetails>
```

Below is the RAML file created.
__customerDetails.raml__
```xml
#%RAML 1.0
title: cusotmer details.
version: v3
baseUri: https://customerdetails.com
mediaType: application/xml

types:
  customerType: !include CustomerTypes.xsd
  customerDetailsXML: !include customerDetailsXML.xml
/customerDetais:
  post:
    body:
      application/xml:
        type: customerType
        example: !include customerDetailsXML.xml
    responses:
```

The above code give me xml validation error at 'example'. Please let me know, what is the wrong in above code snippet. Thank you.

**Comment by ulaBLUE** [comment]
Hi, this issue could be same as [this](https://github.com/raml-org/raml-js-parser-2/issues/580)

**Comment by ddenisenko** [comment]
@badrinathwrk yes, as @ulaBLUE suggested, its the consequences of https://github.com/raml-org/raml-js-parser-2/issues/580 . Please watch this ticket for updates.

**Comment by badrinathwrk** [comment]
Thank you @ulaBLUE and @ddenisenko for quick response. I will follow the ticket.

**Comment by KonstantinSviridov** [comment]
Hi, @badrinathwrk !

It appears that after applying some syntactic corrections to your RAML specification the current parser veriosn does not produce any errors. The corrections are as follows:

1. in "commonTypes.xsd" must be renamed to "CommonTypes.xsd". That's because it is referenced as
`schemaLocation="CommonTypes.xsd"/>` from "CustomerTypes.xsd", not as `schemaLocation="commonTypes.xsd"/>`.

2. in the root element of "CustomerTypes.xsd" one should add `elementFormDefault="qualified"` attribute-value pair:
```xml
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
   targetNamespace="http://www.test.com/request/create"
   xmlns="http://www.test.com/request/create"
   xmlns:com="http://www.test.com/common"
   elementFormDefault="qualified">
```
3. in "customerDetailsXML.xml" one must specify the  "http://www.test.com/request/create" namespace as default for the root element:
```xml
<?xml version="1.0" encoding="utf-8"?>
<customerDetails xmlns="http://www.test.com/request/create">
  <firstName>str1234</firstName>
  <lastName>str12</lastName>
  <language>DE</language>
</customerDetails>
```

Here is a simple example project which process the corrected version of your RAML specification:
[issue589.zip](https://github.com/raml-org/raml-js-parser-2/files/1387858/issue589.zip)

After unzipping execute `npm install` and `npm run test`.

Please, let us know if you have more problems with the parser.

Regards,
Konstantin
