### ISSUE TITLE
Version 1.1.16: Invalid JSON schema: Keyword 'description' is expected to be of type 'string' description,string

### ISSUE THREAD

**Issue by glodieu** [raml-org/raml-js-parser-2#675]
Received this error "Invalid JSON schema: Keyword 'description' is expected to be of type 'string' description,string" when parsing the following RAML file using parser.loadApi method.
Working fine using parser version 1.1.15.

**Comment by ddenisenko** [comment]
I could not reproduce this one. I got an error described in https://github.com/raml-org/raml-js-parser-2/issues/672 , after changing all entries of `"name": "[object Object]"` to `"name": {"type":"string"}` I got no more errors from the parser.

**Comment by glodieu** [comment]
Sorry, wrong Raml file. Attaching the correct one.

**Comment by glodieu** [comment]
[api.txt](https://github.com/raml-org/raml-js-parser-2/files/824395/api.txt)

**Comment by KonstantinSviridov** [comment]
Hi, @glodieu 

In fact, the specification attached contains several incorrect schemas. For examples, instead of 
```
schema: |
              {
                "name": {
                  "type": "string",
                  "required": true
                },
                "description": {
                  "type": "string",
                  "required": false
                }
              }
```
there should be
```
schema: |
              {
                "properties" : {
                "name": {
                  "type": "string",
                  "required": true
                },
                "description": {
                  "type": "string",
                  "required": false
                }
                }
              }
```
Validation passes fine once all such schemas are fixed.

**Comment by sichvoge** [comment]
@KonstantinSviridov are all error messages coming from z-schema? They are not very helpful

**Comment by KonstantinSviridov** [comment]
The corrected specification:
[apiBug1.txt](https://github.com/raml-org/raml-js-parser-2/files/824471/apiBug1.txt)

**Comment by KonstantinSviridov** [comment]
@sichvoge Right, the messages come from z-schema

**Comment by KonstantinSviridov** [comment]
@glodieu You may notice that in your spec there are same style schemas wich do not utilize "description" keyword and do not cause validation problems even if they have a corresponding example. 

Such schemas are syntactically correct but do not reflect what they are supposed to. For example, the first schema in the file is 
```
{
                  "login": {
                    "type": "string",
                    "required": true
                  },
                  "email": {
                    "type": "string",
                    "required": false
                  },
............
                }
```
and it has an example validated against it.

But if you change `login/type` from `string` to `number`, no error would be reported.

This happens because
1. `/login`, `/email` etc defined in root are not understood as properties by the validator and it does not see any property definitions. 
2. By default, without setting `"additionalProperties" : false`, a JOSN object is allowed to have any properties in addition to those difined in `/properties`

Once you change the schema to
```
{
  "properties" : {
                  "login": {
                    "type": "string",
                    "required": true
                  },
                  "email": {
                    "type": "string",
                    "required": false
                  },
............
                }
            }
```
validation starts working.
