### ISSUE TITLE
Version 1.1.17: Invalid JSON schema: Keyword 'type' is expected to be of type 'array,boolean,integer,number,null,object,string'

### ISSUE THREAD

**Issue by glodieu** [raml-org/raml-js-parser-2#693]
Get this error when parsing following api.raml file.
Using parser version 1.1.15 and 1.1.16 doesn't throw any error.

**Comment by glodieu** [comment]
[api.txt](https://github.com/raml-org/raml-js-parser-2/files/828901/api.txt)

**Comment by KonstantinSviridov** [comment]
Hi, @glodieu 

By mistake, in 1.1.16 schemas validation was not enabled for RAML 0.8. That's why there was no error visible. In 1.1.17 warnings were enabled for schema nodes with syntactic JOSN-schema-specific errors (note that there's always an error for schemas which are incorrect as JSON object).

But here we have an error on template parameter value used as schema name in template itself. This case was not considered in 1.1.17 and the fix turns such errors to warnings also. 

Regards, Konstantin.
