### ISSUE TITLE
Error parsing markdown starting with an html tag

### ISSUE THREAD

**Issue by domarmstrong** [raml-org/raml-js-parser-2#70]
Hi, I have some documentation content where the first line starts with an html tag. The parser then throws an error. If I stick a letter in-front of the tag all works again.

```
#%RAML 1.0 DocumentationItem

title: Data API
content: |
  <center>
  ![Black Swan Logo](images/logo_name_bottom.png)
  </center>
```

```
{ code: 7,
  message: 'String is expected documentation/index.raml',
  path: null,
  start: 164,
  end: 188,
  line: 10,
  column: 13,
  range: 
   [ { line: 10, column: 13, position: 164 },
     { line: 10, column: 37, position: 188 } ],
  isWarning: true }
```

**Comment by sichvoge** [comment]
Hi @domarmstrong, thanks for reporting! We will investigate the problem here, but guess its obvious :)

**Comment by ddenisenko** [comment]
Hi @domarmstrong, in latest API Workbench this sample works.

I could not check if it works in the latest JS parser because the released JS parser is failing when trying to parse a fragment, because the fragment parsing API is not released yet. What was JS code to launch a parser against this sample?

**Comment by petrochenko-pavel-a** [comment]
Fixed some time ago, fragment loading works fine with latest RC2.

Regards,
Pavel
