### ISSUE TITLE
Reference could not be resolved

### ISSUE THREAD

**Issue by andyws** [raml-org/raml-js-parser-2#720]
I have the following structure

app.raml
     schemas
          A.json
          B.json

1. app.raml contains the following: type: !include schemas/A.json
2. A.json contains the following: "$ref": "B.json"

This yields: "Reference could not be resolved" as 'schema' is not in the json file path

Amending A.json to : "$ref": "schemas/B.json" results in the same error as 'schema' is in the path twice.

**Comment by KonstantinSviridov** [comment]
Hi, @andyws 

This is definitely a bug which has to be fixed.
For now you may use eqquivalent syntax:
```
body:
  application/json:  !include schemas/A.json
```
for bodies and
```
types:
  myExternalType:  !include schemas/A.json
```
for types defined in the root 'types' field.

Regards,
Konstantin

**Comment by andyws** [comment]
Hi, as I'm keen to resolve this can you suggest which files might be a sensible place to start looking for this bug?

Regards

Andy

**Comment by KonstantinSviridov** [comment]
Well, I'm going to fix it tomorrow, and this is the line I'm going to start with:
https://github.com/raml-org/raml-js-parser-2/blob/master/src/raml1/highLevelImpl.ts#L972

The problem is that the node
```
application/json:
  type: !include schemas/A.json
```
does not itself have include path as value, and `root` appears to be root Api node (which has app.raml unit), while we want `root` to be included AST node (which has schemas/A.json unit).

But right now I'm not sure what exactly to do and that this place is the one to be fixed.
It may appear that before calling `contentProvider()` we should check if the node has a child as
```
  type: !include path/to/schema/sch.json
```
and, if it does, call `contentProvider()` for the child.

We should also keep in mind situations like
```
application/json:
  type:
    type:
      type: !include path/to/schema/sch.json
```
as it's a valid syntax also.

**Comment by KonstantinSviridov** [comment]
Thanks for your report, Andy

The fix will appear in the next release.

Regards,
Konstantin
