### ISSUE TITLE
Parser doesn't parse resourcePathName?

### ISSUE THREAD

**Issue by Dannyys** [raml-org/raml-js-parser-2#722]
I'm trying to read the description of a response in a trait with the following line of code:  
api.allResources()[0].methods()[0].is()[2].trait().responses()[0].description().value();

it returns to me: 
"Some description <<resourcePathName | !singularize | !uppercamelcase>> more description"

Why isn't <<resourcePathName | !singularize | !uppercamelcase>> parsed into the singularized, uppercamelcase form of my resourcePathName?

**Comment by KonstantinSviridov** [comment]
Hi @Dannyys 

Once you've invoked `api.allResources()[0].methods()[0].is()[2].trait()`, you obtain a trait AST node and, thus, by further invoking `.responses()[0].description().value();` you obtain a description of traits responce which, in fact, is "Some description <<resourcePathName | !singularize | !uppercamelcase>> more description".

In order to obtain the methods responces (including those inherited from traits and resource types), you should

1. Obtain an expanded AST node from your `api` node by calling [`api.expand()` method](https://raml-org.github.io/raml-js-parser-2/interfaces/_src_raml1_artifacts_raml10parserapi_.api.html#expand).

2. Invoke `api.allResources()[0].methods()[0].responses()`.

Regards,
Konstantin

**Comment by Dannyys** [comment]
Hello @KonstantinSviridov,

Thank you for explaining the functionality of expanding the Api, this indeed solved the issue I was having.
