### ISSUE TITLE
XML error when parsing from url path

### ISSUE THREAD

**Issue by carowright** [raml-org/raml-js-parser-2#750]
I am getting an unexpected error when parsing this [ramls](https://github.com/raml-org/raml-js-parser-2/files/1047951/api.zip). The error happens when invoking loadApi parser method with path being an url served with the files attached. Our httpResolver returns [api.raml](https://github.com/raml-org/raml-js-parser-2/files/1047993/api.raml.zip). So, the returned content is correct but I get this error:
```
{
  "messageEntry": {
    "code": "INVALID_XML_SCHEMA",
    "message": "Invalid XML schema content"
  },
  "parameters": {},
  "message": "Invalid XML schema content"
}
```
This behaviour is reproducible from version v1.1.14.

**Comment by KonstantinSviridov** [comment]
Hi, @carowright 

I can reproduce the issue with, 1.1.14, but I can not do it with 1.1.21, 1.1.22 and 1.1.23. It seems that it's already fixed.

**Comment by carowright** [comment]
Hi @KonstantinSviridov. 

I tried updating the version to any greater than 1.1.21 and I still get the error

**Comment by KonstantinSviridov** [comment]
Think I need more details for reproducing the issue.

It's hard to guess if custom httpResolver makes any difference, so could you please provide a small project which reveals the error?

I would also ask you to check the test project I use to reproduce the issue, and you may use it as a starting pouint for your example.

[test-npm-project.zip.txt](https://github.com/raml-org/raml-js-parser-2/files/1055425/test-npm-project.zip.txt) (I've added the `.txt` extension as github prohibits me to upload ZIPs for some reason, so remove the `.txt` extension after the file is saved).

The project is installed by executing `npm install` in the project root.
The main script is run by executing `node script.js` in the project root.

The main script loads one by one local copies of [api.raml](https://github.com/raml-org/raml-js-parser-2/files/1047993/api.raml.zip) and notificatieservice.raml from [ramls archive](https://github.com/raml-org/raml-js-parser-2/files/1047951/api.zip) and prints their JSON representations so that we could see errors.

The project uses 1.1.21 parser, and It does not produce errors for both files. Do you observe the same?

In order to change parser version, one should
* remove `node_modules` folder of the project completely
* change parser version in `package.json`
* execute `npm install` in the project root

After changing parser version to 1.1.14 errors appear for notificatieservice.raml from [ramls archive](https://github.com/raml-org/raml-js-parser-2/files/1047951/api.zip). Do you observe the same?

**Comment by dlarralde** [comment]
Hi @KonstantinSviridov.

We were able to reproduce it. The only thing you need to do is to change the name of the file from api.raml to apiraml in the script.js and then rename the file.

I've upload the same project with these changes.

Thanks!

[test-npm-project 2.zip.txt](https://github.com/raml-org/raml-js-parser-2/files/1061504/test-npm-project.2.zip.txt)
