### ISSUE TITLE
1.1.25 is not usable !

### ISSUE THREAD

**Issue by m31271n** [raml-org/raml-js-parser-2#755]
Just install it. You will find `dist` directory is not included.

**Comment by eliasmamo** [comment]
I agree it has broken my build

**Comment by connor4312** [comment]
`npm unpublish` would be appropriate here!

**Comment by t1maccapp** [comment]
Same problem

**Comment by sichvoge** [comment]
I can confirm that behaviour. Sorry about that guys. We will investigate what happened as soon as possible.

**Comment by ddenisenko** [comment]
1.1.25 npm release was unpublished. 1.1.25 browser npm, bower and browser version archive remain intact.

[1.1.26 release](https://github.com/raml-org/raml-js-parser-2/releases/tag/1.1.26) was published instead, being functionally equal to 1.1.25. 

We are sorry, guys.

**Comment by m31271n** [comment]
@ddenisenko `files` attribute in `package.json` is a good thing to avaid this kind of problems.

**Comment by ddenisenko** [comment]
@m31271n so, if I put something to `files`, and that something does not exist, `npm publish` is going to fail?

**Comment by ddenisenko** [comment]
Anyway, this probably wouldn't help in this case, because there 4 different types of distributions for raml parser, and all 4 are based on `dist` folder. 

3 of those are okay, 1 (pure npm) for some reason does not include `dist`. So at the moment of publishing `dist` did exist for sure. It is explicitly allowed in `.npmingore`.

**Comment by m31271n** [comment]
Test on the condition which you described, It is not going to fail. So, forget it. ;]

**Comment by connor4312** [comment]
Thanks guys! 😄
