### ISSUE TITLE
Library import in uses is not populating the actual items in the parse result

### ISSUE THREAD

**Issue by kokyhin** [raml-org/raml-js-parser-2#770]
For example if in raml file we have included types
```
types:
  myType: !include /types/myType.yaml
```

In parsed object we will have populated types with content from referenced files.
The same behavior doesn't apply to libraries.

For example if i use:
```
uses:
  myLib: libraries/myLib.raml
```

i will receive in object {key: 'myLib', value: 'libraries/myLib.raml'} in resulting object 'uses' property

Please advise if that is a desired behavior or is a bug?

**Comment by eliasmamo** [comment]
I confirm, when trying to import libraries have the same issue.

**Comment by KonstantinSviridov** [comment]
Hi guys!

In fact, what you see is an expected behavior.

If you need library content, you should manually resolve its path and then use it as input for `loadRAML` or `loadRAMLSync` method.

But in most cases you do not need loading any library because both Api and Library provide the `expand` method. Calling `api.expand(true)` would contribute all components from libraries into the resulting api. See more about [library expansion](https://github.com/raml-org/raml-js-parser-2/issues/371).

Regards,
Konstantin
