### ISSUE TITLE
xml validation incorrect.

### ISSUE THREAD

**Issue by WAvdBeek** [raml-org/raml-js-parser-2#772]
also as part of the ATOM IDE.

We took a sample valid XSD’s  and XML’s from w3schools.com ( https://www.w3schools.com/xml/schema_example.asp)

XSD File: shiporder.xsd
XML File: shiporder.xml

![atom xsd issue](https://user-images.githubusercontent.com/10404244/28013055-adc54968-655f-11e7-9a1f-9e4d3e082601.jpg)

**Comment by KonstantinSviridov** [comment]
Hi, @WAvdBeek !

For me the 1.1.26 parser validates the examples correctly.

I've created an sample project which involves the 'shiporder.xml' example and three versions of 'shiporder.xsd' schema. The simplest version of the schema contains one mistake -- in order to make us know that validation is actually enabled.

[xml-test.zip](https://github.com/raml-org/raml-js-parser-2/files/1139504/xml-test.zip)

Could you please check if the test script is executed fine for you or not.
It's
```
npm install
npm run test
```
You should see the following output:
```
The 1.0 API has 1 errors
[
  "Content is not valid according to schema: file_0.xml:1: element name: Schemas validity error : Element 'name': 'Ola Nordmann' is not a valid value of the atomic type 'xs:integer'."
]
The 0.8 API has 1 errors
[
  "Content is not valid according to schema: file_0.xml:8: element name: Schemas validity error : Element 'name': 'Ola Nordmann' is not a valid value of the atomic type 'xs:integer'."
]
```

Regards,
Konstantin

**Comment by WAvdBeek** [comment]
running the script works.
after updating the "Api workbench" plugin in ATOM this also gives now just 1 error.
![atom-xsd-issue2](https://user-images.githubusercontent.com/10404244/28965372-b1aa4d28-7908-11e7-91ac-170458e3e4d7.png)
hence the error is different and not usefull, but that is not an issue of this library.

**Comment by KonstantinSviridov** [comment]
Great!

Thanks for checking it.
